# Generated by Django 5.2.4 on 2025-08-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AstroResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astro', models.CharField(help_text="Keyword or tag, e.g. 'aries' or 'career'", max_length=100, unique=True)),
                ('response', models.TextField(help_text='Authoritative response text you want the bot to use/prefer')),
            ],
            options={
                'ordering': ['astro'],
            },
        ),
    ]
