# Generated by Django 5.2.4 on 2025-08-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AstroResponse',
        ),
    ]
