questions = [
 "I am not a worrier.",
    "I like to have a lot of people around me.",
    "I enjoy concentrating on a fantasy or daydream and exploring all its possibilities, letting it grow and develop.",
    "I try to be courteous to everyone I meet.",
    "I keep my belongings neat and clean.",
    "At times I have felt bitter and resentful.",
    "I laugh easily.",
    "I think it's interesting to learn and develop new hobbies.",
    "At times I bully or flatter people into doing what I want them to.",
    "I'm pretty good about pacing myself so as to get things done on time.",
    "When I'm under a great deal of stress, sometimes I feel like I'm going to pieces.",
    "I prefer jobs that let me work alone without being bothered by other people.",
    "I am intrigued by the patterns I find in art and nature.",
    "Some people think I'm selfish and egotistical.",
    "I often come into situations without being fully prepared.",
    "I rarely feel lonely or blue.",
    "I enjoy really talking to people.",
    "I believe letting students hear controversial speakers can only confuse and mislead them.",
    "If someone starts a fight, I'm ready to fight back.",
    "I try to perform all the tasks assigned to me conscientiously.",
    "I often feel tense and jittery.",
    "I like to be where the action is.",
    "Poetry has little or no effect on me.",
    "I'm better than most people, and I know it.",
    "I have a clear set of goals and work toward them in an orderly fashion.",
    "Sometimes I feel completely worthless.",
    "I shy away from crowds of people.",
    "I would have difficulty just letting my mind wander without control or guidance.",
    "When I've been insulted, I just try to forgive and forget.",
    "I waste a lot of time before settling down to work.",
    "I rarely feel fearful or anxious.",
    "I often feel as if I'm bursting with energy.",
    "I seldom notice the moods or feelings that different environments produce.",
    "I tend to assume the best about people.",
    "I work hard to accomplish my goals.",
    "I often get angry at the way people treat me.",
    "I am a cheerful, high-spirited person.",
    "I experience a wide range of emotions or feelings.",
    "Some people think of me as cold and calculating.",
    "When I make a commitment, I can always be counted on to follow through.",
    "Too often, when things go wrong, I get discouraged and feel like giving up.",
    "I don’t get much pleasure from chatting with people.",
    "Sometimes when I am reading poetry or looking at a work of art, I feel a chill or wave of excitement.",
    "I have no sympathy for beggars.",
    "Sometimes I’m not as dependable or reliable as I should be.",
    "I am seldom sad or depressed.",
    "My life is fast-paced.",
    "I have little interest in speculating on the nature of the universe or the human condition.",
    "I generally try to be thoughtful and considerate.",
    "I am a productive person who always gets the job done.",
    "I often feel helpless and want someone else to solve my problems.",
    "I am a very active person.",
    "I have a lot of intellectual curiosity.",
    "If I don’t like people, I let them know it.",
    "I never seem to be able to get organized.",
    "At times I have been so ashamed I just wanted to hide.",
    "I would rather go my own way than be a leader of others.",
    "I often enjoy playing with theories or abstract ideas.",
    "If necessary, I am willing to manipulate people to get what I want.",
    "I strive for excellence in everything I do.",   
]